name: YouTube Live Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files (VERY IMPORTANT)
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -al

      - name: Download FFmpeg (static)
        run: |
          curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz
          tar -xf ffmpeg.tar.xz
          cd ffmpeg-*-amd64-static
          sudo cp ffmpeg /usr/bin/
          sudo cp ffprobe /usr/bin/

      - name: Verify FFmpeg
        run: |
          which ffmpeg
          ffmpeg -version

      - name: Test video file
        run: |
          ffmpeg -i video.mp4 || true

      - name: Start YouTube Stream
        run: |
            ffmpeg -re -stream_loop -1 -i video.mp4 \
            -vf "scale=854:480,fps=25" \
            -c:v libx264 -preset ultrafast -b:v 1200k \
            -pix_fmt yuv420p -g 50 \
            -c:a aac -b:a 96k \
            -f flv rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}
